### PR TITLE
Clarify that this is a deployed format.

### PR DESCRIPTION
**Pull request by wkumari**
Make it clearer that this is deployed / in use, and so we cannot realistically make changes to the format.

### CODE REVIEW

**Comment by ekline** [comment]
[nit] I think just "currently deployed format" maybe is sufficient (as opposed to "system / format").

[nit] Now that I read it, "where their prefixes live" seems maybe a little too casual?  "where their prefixes should be geolocated"? idk.

Otherwise, LGTM (especially if you run "make" and thereby update the draft.txt file).

Thanks.

**Comment by wkumari** [comment]
Thanks Erik, I've addressed these.

**Comment by ekline** [comment]
Thanks.

[nit] s/deployed system format/deployed format/

Looks like you tightened up differently in the two different locations.

**Comment by wkumari** [comment]
Doh! Thank you - sorry for missing it.

Fixed. Also cleaned up the long lines in the IETF comment, and reiterated again that this is deployed and used.

**Comment by ekline** [comment]
LGTM. Thanks!

**Comment by ekline** [comment]
@panmari

**Comment by panmari** [comment]
LGTM, thanks for the update!

**Pull request merged**
